// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect;

namespace Proiect.Migrations
{
    [DbContext(typeof(DomContextcs))]
    partial class DomContextcsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14");

            modelBuilder.Entity("Proiect.Domeniu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Denumire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descriere")
                        .HasColumnType("TEXT");

                    b.Property<int>("nrCarti")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Domenii");
                });

            modelBuilder.Entity("Proiect.carte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DomeniuId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("an_aparitie")
                        .HasColumnType("TEXT");

                    b.Property<string>("autor")
                        .HasColumnType("TEXT");

                    b.Property<string>("editura")
                        .HasColumnType("TEXT");

                    b.Property<int>("livrare")
                        .HasColumnType("INTEGER");

                    b.Property<float>("pret")
                        .HasColumnType("REAL");

                    b.Property<string>("titlu")
                        .HasColumnType("TEXT");

                    b.Property<float>("valoare")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DomeniuId");

                    b.ToTable("carte");
                });

            modelBuilder.Entity("Proiect.carte", b =>
                {
                    b.HasOne("Proiect.Domeniu", null)
                        .WithMany("carti")
                        .HasForeignKey("DomeniuId");
                });
#pragma warning restore 612, 618
        }
    }
}
